/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as ApiPublicDaydreamWhepRouteImport } from './routes/api/public/daydream-whep'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDaydreamWhepRoute = ApiPublicDaydreamWhepRouteImport.update({
  id: '/api/public/daydream-whep',
  path: '/api/public/daydream-whep',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gdpr': typeof GdprRoute
  '/r/$id': typeof RIdRoute
  '/api/public/daydream-whep': typeof ApiPublicDaydreamWhepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gdpr': typeof GdprRoute
  '/r/$id': typeof RIdRoute
  '/api/public/daydream-whep': typeof ApiPublicDaydreamWhepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gdpr': typeof GdprRoute
  '/r/$id': typeof RIdRoute
  '/api/public/daydream-whep': typeof ApiPublicDaydreamWhepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gdpr' | '/r/$id' | '/api/public/daydream-whep'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gdpr' | '/r/$id' | '/api/public/daydream-whep'
  id: '__root__' | '/' | '/gdpr' | '/r/$id' | '/api/public/daydream-whep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GdprRoute: typeof GdprRoute
  RIdRoute: typeof RIdRoute
  ApiPublicDaydreamWhepRoute: typeof ApiPublicDaydreamWhepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daydream-whep': {
      id: '/api/public/daydream-whep'
      path: '/api/public/daydream-whep'
      fullPath: '/api/public/daydream-whep'
      preLoaderRoute: typeof ApiPublicDaydreamWhepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GdprRoute: GdprRoute,
  RIdRoute: RIdRoute,
  ApiPublicDaydreamWhepRoute: ApiPublicDaydreamWhepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
