/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaniRouteImport } from './routes/bani'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoneazaRouteImport } from './routes/doneaza'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as V2RouteImport } from './routes/v2'
import { Route as ApiBaldRouteImport } from './routes/api/bald'
import { Route as ApiFalRouteImport } from './routes/api/fal'
import { Route as ApiMirrorFrameRouteImport } from './routes/api/mirror-frame'
import { Route as RIdRouteImport } from './routes/r.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaniRoute = BaniRouteImport.update({
  id: '/bani',
  path: '/bani',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneazaRoute = DoneazaRouteImport.update({
  id: '/doneaza',
  path: '/doneaza',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaldRoute = ApiBaldRouteImport.update({
  id: '/api/bald',
  path: '/api/bald',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFalRoute = ApiFalRouteImport.update({
  id: '/api/fal',
  path: '/api/fal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMirrorFrameRoute = ApiMirrorFrameRouteImport.update({
  id: '/api/mirror-frame',
  path: '/api/mirror-frame',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bani': typeof BaniRoute
  '/dashboard': typeof DashboardRoute
  '/doneaza': typeof DoneazaRoute
  '/gdpr': typeof GdprRoute
  '/v2': typeof V2Route
  '/api/bald': typeof ApiBaldRoute
  '/api/fal': typeof ApiFalRoute
  '/api/mirror-frame': typeof ApiMirrorFrameRoute
  '/r/$id': typeof RIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bani': typeof BaniRoute
  '/dashboard': typeof DashboardRoute
  '/doneaza': typeof DoneazaRoute
  '/gdpr': typeof GdprRoute
  '/v2': typeof V2Route
  '/api/bald': typeof ApiBaldRoute
  '/api/fal': typeof ApiFalRoute
  '/api/mirror-frame': typeof ApiMirrorFrameRoute
  '/r/$id': typeof RIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bani': typeof BaniRoute
  '/dashboard': typeof DashboardRoute
  '/doneaza': typeof DoneazaRoute
  '/gdpr': typeof GdprRoute
  '/v2': typeof V2Route
  '/api/bald': typeof ApiBaldRoute
  '/api/fal': typeof ApiFalRoute
  '/api/mirror-frame': typeof ApiMirrorFrameRoute
  '/r/$id': typeof RIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bani'
    | '/dashboard'
    | '/doneaza'
    | '/gdpr'
    | '/v2'
    | '/api/bald'
    | '/api/fal'
    | '/api/mirror-frame'
    | '/r/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bani'
    | '/dashboard'
    | '/doneaza'
    | '/gdpr'
    | '/v2'
    | '/api/bald'
    | '/api/fal'
    | '/api/mirror-frame'
    | '/r/$id'
  id:
    | '__root__'
    | '/'
    | '/bani'
    | '/dashboard'
    | '/doneaza'
    | '/gdpr'
    | '/v2'
    | '/api/bald'
    | '/api/fal'
    | '/api/mirror-frame'
    | '/r/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaniRoute: typeof BaniRoute
  DashboardRoute: typeof DashboardRoute
  DoneazaRoute: typeof DoneazaRoute
  GdprRoute: typeof GdprRoute
  V2Route: typeof V2Route
  ApiBaldRoute: typeof ApiBaldRoute
  ApiFalRoute: typeof ApiFalRoute
  ApiMirrorFrameRoute: typeof ApiMirrorFrameRoute
  RIdRoute: typeof RIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bani': {
      id: '/bani'
      path: '/bani'
      fullPath: '/bani'
      preLoaderRoute: typeof BaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doneaza': {
      id: '/doneaza'
      path: '/doneaza'
      fullPath: '/doneaza'
      preLoaderRoute: typeof DoneazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bald': {
      id: '/api/bald'
      path: '/api/bald'
      fullPath: '/api/bald'
      preLoaderRoute: typeof ApiBaldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fal': {
      id: '/api/fal'
      path: '/api/fal'
      fullPath: '/api/fal'
      preLoaderRoute: typeof ApiFalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mirror-frame': {
      id: '/api/mirror-frame'
      path: '/api/mirror-frame'
      fullPath: '/api/mirror-frame'
      preLoaderRoute: typeof ApiMirrorFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaniRoute: BaniRoute,
  DashboardRoute: DashboardRoute,
  DoneazaRoute: DoneazaRoute,
  GdprRoute: GdprRoute,
  V2Route: V2Route,
  ApiBaldRoute: ApiBaldRoute,
  ApiFalRoute: ApiFalRoute,
  ApiMirrorFrameRoute: ApiMirrorFrameRoute,
  RIdRoute: RIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
