/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BaniRouteImport } from './routes/bani'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoneazaRouteImport } from './routes/doneaza'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as V4RouteImport } from './routes/v4'
import { Route as AuthenticatedRemoteRouteImport } from './routes/_authenticated/remote'
import { Route as ApiBaldRouteImport } from './routes/api/bald'
import { Route as ApiFalRouteImport } from './routes/api/fal'
import { Route as ApiMirrorFrameRouteImport } from './routes/api/mirror-frame'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as ApiPublicKioskSyncRouteImport } from './routes/api/public/kiosk-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BaniRoute = BaniRouteImport.update({
  id: '/bani',
  path: '/bani',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneazaRoute = DoneazaRouteImport.update({
  id: '/doneaza',
  path: '/doneaza',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const V4Route = V4RouteImport.update({
  id: '/v4',
  path: '/v4',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRemoteRoute = AuthenticatedRemoteRouteImport.update({
  id: '/remote',
  path: '/remote',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiBaldRoute = ApiBaldRouteImport.update({
  id: '/api/bald',
  path: '/api/bald',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFalRoute = ApiFalRouteImport.update({
  id: '/api/fal',
  path: '/api/fal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMirrorFrameRoute = ApiMirrorFrameRouteImport.update({
  id: '/api/mirror-frame',
  path: '/api/mirror-frame',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKioskSyncRoute = ApiPublicKioskSyncRouteImport.update({
  id: '/api/public/kiosk-sync',
  path: '/api/public/kiosk-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bani': typeof BaniRoute
  '/dashboard': typeof DashboardRoute
  '/doneaza': typeof DoneazaRoute
  '/gdpr': typeof GdprRoute
  '/v4': typeof V4Route
  '/remote': typeof AuthenticatedRemoteRoute
  '/api/bald': typeof ApiBaldRoute
  '/api/fal': typeof ApiFalRoute
  '/api/mirror-frame': typeof ApiMirrorFrameRoute
  '/r/$id': typeof RIdRoute
  '/api/public/kiosk-sync': typeof ApiPublicKioskSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bani': typeof BaniRoute
  '/dashboard': typeof DashboardRoute
  '/doneaza': typeof DoneazaRoute
  '/gdpr': typeof GdprRoute
  '/v4': typeof V4Route
  '/remote': typeof AuthenticatedRemoteRoute
  '/api/bald': typeof ApiBaldRoute
  '/api/fal': typeof ApiFalRoute
  '/api/mirror-frame': typeof ApiMirrorFrameRoute
  '/r/$id': typeof RIdRoute
  '/api/public/kiosk-sync': typeof ApiPublicKioskSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bani': typeof BaniRoute
  '/dashboard': typeof DashboardRoute
  '/doneaza': typeof DoneazaRoute
  '/gdpr': typeof GdprRoute
  '/v4': typeof V4Route
  '/_authenticated/remote': typeof AuthenticatedRemoteRoute
  '/api/bald': typeof ApiBaldRoute
  '/api/fal': typeof ApiFalRoute
  '/api/mirror-frame': typeof ApiMirrorFrameRoute
  '/r/$id': typeof RIdRoute
  '/api/public/kiosk-sync': typeof ApiPublicKioskSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bani'
    | '/dashboard'
    | '/doneaza'
    | '/gdpr'
    | '/v4'
    | '/remote'
    | '/api/bald'
    | '/api/fal'
    | '/api/mirror-frame'
    | '/r/$id'
    | '/api/public/kiosk-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bani'
    | '/dashboard'
    | '/doneaza'
    | '/gdpr'
    | '/v4'
    | '/remote'
    | '/api/bald'
    | '/api/fal'
    | '/api/mirror-frame'
    | '/r/$id'
    | '/api/public/kiosk-sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bani'
    | '/dashboard'
    | '/doneaza'
    | '/gdpr'
    | '/v4'
    | '/_authenticated/remote'
    | '/api/bald'
    | '/api/fal'
    | '/api/mirror-frame'
    | '/r/$id'
    | '/api/public/kiosk-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BaniRoute: typeof BaniRoute
  DashboardRoute: typeof DashboardRoute
  DoneazaRoute: typeof DoneazaRoute
  GdprRoute: typeof GdprRoute
  V4Route: typeof V4Route
  ApiBaldRoute: typeof ApiBaldRoute
  ApiFalRoute: typeof ApiFalRoute
  ApiMirrorFrameRoute: typeof ApiMirrorFrameRoute
  RIdRoute: typeof RIdRoute
  ApiPublicKioskSyncRoute: typeof ApiPublicKioskSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bani': {
      id: '/bani'
      path: '/bani'
      fullPath: '/bani'
      preLoaderRoute: typeof BaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doneaza': {
      id: '/doneaza'
      path: '/doneaza'
      fullPath: '/doneaza'
      preLoaderRoute: typeof DoneazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4': {
      id: '/v4'
      path: '/v4'
      fullPath: '/v4'
      preLoaderRoute: typeof V4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/remote': {
      id: '/_authenticated/remote'
      path: '/remote'
      fullPath: '/remote'
      preLoaderRoute: typeof AuthenticatedRemoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/bald': {
      id: '/api/bald'
      path: '/api/bald'
      fullPath: '/api/bald'
      preLoaderRoute: typeof ApiBaldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fal': {
      id: '/api/fal'
      path: '/api/fal'
      fullPath: '/api/fal'
      preLoaderRoute: typeof ApiFalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mirror-frame': {
      id: '/api/mirror-frame'
      path: '/api/mirror-frame'
      fullPath: '/api/mirror-frame'
      preLoaderRoute: typeof ApiMirrorFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk-sync': {
      id: '/api/public/kiosk-sync'
      path: '/api/public/kiosk-sync'
      fullPath: '/api/public/kiosk-sync'
      preLoaderRoute: typeof ApiPublicKioskSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRemoteRoute: typeof AuthenticatedRemoteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRemoteRoute: AuthenticatedRemoteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BaniRoute: BaniRoute,
  DashboardRoute: DashboardRoute,
  DoneazaRoute: DoneazaRoute,
  GdprRoute: GdprRoute,
  V4Route: V4Route,
  ApiBaldRoute: ApiBaldRoute,
  ApiFalRoute: ApiFalRoute,
  ApiMirrorFrameRoute: ApiMirrorFrameRoute,
  RIdRoute: RIdRoute,
  ApiPublicKioskSyncRoute: ApiPublicKioskSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
